import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import * as core from '../public/core.js';
const source=(await readFile(new URL('../public/app.js',import.meta.url),'utf8')).replace(/^import .*\n/gm,'').split("window.addEventListener('beforeunload'")[0];
function ui(){const context=vm.createContext({...core,localStorage:{getItem:()=> 'en'},document:{querySelector:()=>null},isDemo:()=>true,configured:false});vm.runInContext(source,context);vm.runInContext('cached=sampleData().map(r=>({...r.payload,id:r.id,kind:r.kind}));',context);return expression=>vm.runInContext(expression,context)}
function uniqueIds(html){const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size,'Duplicate form/filter IDs');}
test('three tabs expose integrated registers and entry forms without duplicate IDs',()=>{const run=ui();assert.equal(run('nav.length'),3);for(const [fn,forms] of [['overviewPage',['addstudent','addteacher','search','teacherStatus']],['attendanceGrowthPage',['attendanceForm','growthForm','date','month']],['assessmentPage',['assessmentForm','period','subject']]]){const html=run(fn+'()');uniqueIds(html);for(const id of forms)assert.ok(html.includes(`id="${id}"`),id);}});
test('student and teacher register filters and removal controls',()=>{const run=ui();assert.ok(run('overviewPage()').includes('data-removestudent'));assert.ok(run('overviewPage()').includes('data-removeteacher'));run("grade='LKG';search='Sample student 1';studentStatus='left'");assert.ok(!run('studentPage()').includes('data-editstudent'));run("teacherStatus='inactive'");assert.ok(!run('teacherPage()').includes('data-editteacher'));});
test('empty assessment data has no invented progress',()=>{const run=ui();run("cached=cached.filter(r=>r.kind!=='assessment')");const html=run('assessmentPage()');assert.ok(html.includes('0 matched scores'));assert.ok(html.includes('Missing scores'));});
test('saving one form preserves the other form draft and dirty state',async()=>{const run=ui();run(`globalThis.fields=[{dataset:{weight:'V001'},value:'19.5',matches:()=>false}];document.querySelectorAll=()=>fields;saveBatch=async()=>{};toast=()=>{};render=()=>{fields=[{dataset:{weight:'V001'},value:'12',matches:()=>false}]};dirtyForms.add('attendanceForm');dirtyForms.add('growthForm');dirty=true;`);await run("commit([], 'attendanceForm')");assert.equal(run('fields[0].value'),'19.5');assert.equal(run('dirty'),true);assert.equal(run("dirtyForms.has('attendanceForm')"),false);assert.equal(run("dirtyForms.has('growthForm')"),true);});
test('demographic charts group communities without inventing missing values',()=>{const run=ui();run("cached=cached.filter(r=>r.kind==='student').slice(0,3);cached[0].community='  Group A ';cached[1].community='group   a';cached[2].community='';");const html=run('demographicCharts(cached)');assert.ok(html.includes('Group A</span><strong>2'));assert.ok(html.includes('Not recorded</span><strong>1'));assert.ok(html.includes('67%'));assert.ok(html.includes('Gender distribution by class'));assert.ok(html.includes('Age distribution'));});
test('charts respect class filter and handle empty selections',()=>{const run=ui();run("grade='LKG'");const html=run('overviewPage()');assert.ok(html.includes('15 students'));assert.ok(!run('demographicCharts([])').includes('NaN'));assert.ok(run('demographicCharts([])').includes('No records for this selection.'));});
