import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import * as core from '../public/core.js';
const source=(await readFile(new URL('../public/app.js',import.meta.url),'utf8')).replace(/^import .*\n/gm,'').split("window.addEventListener('beforeunload'")[0];
function ui(){const context=vm.createContext({...core,localStorage:{getItem:()=> 'en'},document:{querySelector:()=>null},isDemo:()=>true,configured:false});vm.runInContext(source,context);vm.runInContext(`cached=sampleData().map(r=>({...r.payload,id:r.id,kind:r.kind}));academicYear=currentAcademicYear();overviewData={students:cached.filter(r=>r.kind==='student').map(r=>({student_id:r.id,student_name:r.name,enrollment_year:academicYear,gender:r.sex==='F'?'Female':'Male',date_of_birth:r.dob,social_category:r.community,program_type:'KC2'})),enrollments:cached.filter(r=>r.kind==='student').map(r=>({student_id:r.id,academic_year:academicYear,grade:r.grade})),staff:cached.filter(r=>r.kind==='teacher').map(r=>({staff_id:r.id,staff_name:r.name,staff_role:r.role==='School lead'?'Leadership':'Teacher',email:null,phone:null,grades:r.grades,subjects:r.subjects,joined_on:null,left_on:null,active:r.active}))};`,context);return expression=>vm.runInContext(expression,context)}
function uniqueIds(html){const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size,'Duplicate form/filter IDs');}
test('three tabs expose integrated registers and entry actions without duplicate IDs',()=>{const run=ui();assert.equal(run('nav.length'),3);for(const [fn,controls] of [['overviewPage',['addOverviewStaff','addOverviewStudent','academicYear','search','studentRegisterGrade','studentEnrollmentYear','teacherStatus']],['attendanceGrowthPage',['attendanceForm','growthForm','term','date','attendanceGrade','attendanceMonth','growthGrade','growthMonth']],['assessmentPage',['assessmentForm','period','subject']]]){const html=run(fn+'()');uniqueIds(html);for(const id of controls)assert.ok(html.includes(`id="${id}"`),id);}});
test('normalized student and staff registers expose edit controls and filters',()=>{const run=ui();const html=run('overviewPage()'),student=run('inlineStudentForm()');assert.ok(html.includes('data-edit-overview-student'));assert.ok(html.includes('data-edit-overview-staff'));assert.ok(student.includes('Enrollment year'));assert.ok(student.includes('Program type'));run("grade='LKG';search='Sample student 1'");assert.ok(run('overviewStudents().length')>0);run("studentRegisterGrade='UKG'");assert.equal(run('overviewStudentRegister(overviewStudents()).length'),0);run("studentRegisterGrade='LKG';studentEnrollmentYear='1900-01'");assert.equal(run('overviewStudentRegister(overviewStudents()).length'),0);run("teacherStatus='inactive'");assert.equal(run('overviewStaff().length'),0);});
test('student and staff entry forms render only inside add or edit dialogs',()=>{const run=ui();const page=run('overviewPage()');assert.ok(!page.includes('id="overviewStaffForm"'));assert.ok(!page.includes('id="overviewStudentForm"'));const staff=run('inlineStaffForm()'),student=run('inlineStudentForm()');uniqueIds(staff);uniqueIds(student);assert.ok(staff.includes('id="overviewStaffForm"'));assert.ok(student.includes('id="overviewStudentForm"'));assert.ok(staff.includes('id="cancelStaffEdit"'));assert.ok(student.includes('id="cancelStudentEdit"'));});
test('overview distinguishes all student profiles from selected-year enrollment',()=>{const run=ui();const html=run('overviewPage()');assert.ok(html.includes('Total students'));assert.ok(html.includes('All student profiles'));assert.ok(html.includes('Enrolled students'));assert.equal(run('overviewData.students.length'),run('overviewStudents().length'));run('overviewData.enrollments=[]');assert.ok(run('overviewData.students.length')>0);assert.equal(run('overviewStudents().length'),0);});
test('empty assessment data has no invented progress',()=>{const run=ui();run("cached=cached.filter(r=>r.kind!=='assessment')");const html=run('assessmentPage()');assert.ok(html.includes('0 matched scores'));assert.ok(html.includes('Missing scores'));});
test('saving one form preserves the other form draft and dirty state',async()=>{const run=ui();run(`globalThis.fields=[{dataset:{weight:'V001'},value:'19.5',matches:()=>false}];document.querySelectorAll=()=>fields;saveBatch=async()=>{};toast=()=>{};render=()=>{fields=[{dataset:{weight:'V001'},value:'12',matches:()=>false}]};dirtyForms.add('attendanceForm');dirtyForms.add('growthForm');dirty=true;`);await run("commit([], 'attendanceForm')");assert.equal(run('fields[0].value'),'19.5');assert.equal(run('dirty'),true);assert.equal(run("dirtyForms.has('attendanceForm')"),false);assert.equal(run("dirtyForms.has('growthForm')"),true);});
test('demographic charts use compact vertical bars without inventing missing values',()=>{const run=ui();run("cached=cached.filter(r=>r.kind==='student').slice(0,3);cached[0].community='  Group A ';cached[1].community='group   a';cached[2].community='';");const html=run('demographicCharts(cached)');assert.ok(html.includes('class="vchart"'));assert.ok(html.includes('class="vchart gender-vchart"'));assert.ok(html.includes('Group A'));assert.ok(html.includes('Not recorded'));assert.ok(html.includes('67%'));assert.ok(html.includes('Gender distribution by class'));assert.ok(html.includes('Age distribution'));});
test('overview omits program and staffing charts while bars show value callouts',()=>{const run=ui();const html=run('overviewPage()');assert.ok(!html.includes('<h2>Program type</h2>'));assert.ok(!html.includes('Class staffing'));assert.ok(html.includes('class="vbar-value"'));assert.ok(html.includes('class="vbar-fill"'));});
test('charts respect class filter and handle empty selections',()=>{const run=ui();run("grade='LKG'");const html=run('overviewPage()');assert.ok(html.includes('15 students'));assert.ok(!run('demographicCharts([])').includes('NaN'));assert.ok(run('demographicCharts([])').includes('No records for this selection.'));});
test('attendance and growth insights use three-month terms and class-level charts',()=>{const run=ui();assert.deepEqual([...run("termMonths('2026-T1')")],['2026-06','2026-07','2026-08']);assert.deepEqual([...run("termMonths('2026-T3')")],['2026-12','2027-01','2027-02']);const html=run('attendanceGrowthPage()');assert.ok(html.includes('Attendance category by class'));assert.ok(html.includes('Irregular attendance and low BMI by class'));assert.ok(!html.includes('Attendance and growth by student'));assert.ok(html.includes('Regular (&gt;70%)'));assert.ok(html.includes('Irregular (≤70%)'));});
test('community choices include the requested categories and preserve existing values',()=>{const run=ui();for(const label of ['SC','ST','MBC','BC','General','Others'])assert.ok(run('communityOptions()').includes('value="'+label+'"'));assert.ok(run('communityOptions()').includes('Not recorded'));assert.ok(run("communityOptions('ST')").includes('value="ST" selected'));assert.ok(run("communityOptions('Existing community')").includes('value="Existing community" selected'));});
